### ISSUE TITLE
Desenvolver o documento de Roadmap do produto

### ISSUE THREAD

**Issue by HianPraxedes** [fga-eps-mds/Tema-02#43]
### Descrição:
Desenvolver o documento de Roadmap do produto.

### Tarefas:

- [x]  Definir o modelo do documento.
- [x]  Dividir entre os membros as tarefas individuais a serem feitas.

### Critérios de aceitação:

- [x] Revisão do documento.
- [x] Documento deve estar no repositório do git.

**Comment by ahbreu** [comment]
[Roadmap](https://unbbr-my.sharepoint.com/:x:/g/personal/190036605_aluno_unb_br/ESSSzthGKQ9DqcCTb4VzP_oBcSUXJoKMeCBgQscH-KmNaQ)
